title: Fundamental Research team
description: We are a research team in DAMO Academy, Alibaba Group, dedicated to developing next generation computer vision algorithms and technologies.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
